### ISSUE TITLE
About evaluation on the other datasets

### ISSUE THREAD

**Issue by YellowBe** [gmberton/CosPlace#13]
Hello gmberton, if you can give me an example of testing Cosplace on pittsburgh to get the recall? To be honest, if you can give the recall@10 on Pitts250k, Pitts30k, Tokyo 24/7, MSLS, it will be the best.
Thank you very much!

**Comment by gmberton** [comment]
Hello, here are the results on those datasets using a VGG-16 with output dimension 512

| Dataset    |  R@1 |  R@5 | R@10 | R@20 |
|------------|------|------|------|------|
| Pitts 250k | 89.7 | 96.4 | 97.7 | 98.4 |
| Pitts 30k  | 88.5 | 94.5 | 95.7 | 96.7 |
| Tokyo 24/7 | 82.8 | 90.0 | 93.3 | 95.8 |
| MSLS       | 79.5 | 87.2 | 89.5 | 91.5 |


And here are the results with a ResNet-101 with output dimension 2048

| Dataset    |  R@1 |  R@5 | R@10 | R@20 |
|------------|------|------|------|------|
| Pitts 250k | 91.8 | 97.5 | 98.6 | 98.9 |
| Pitts 30k  | 90.4 | 95.7 | 96.7 | 97.4 |
| Tokyo 24/7 | 88.6 | 95.9 | 96.5 | 96.5 |
| MSLS       | 86.6 | 92.0 | 93.4 | 94.7 |

**Comment by YellowBe** [comment]
Thanks a lot!
