### ISSUE TITLE
About evaluation in SF-XL

### ISSUE THREAD

**Issue by ShihaoShao-GH** [gmberton/CosPlace#15]
Thanks for your great work! I am very impressed by your awesome SF-XL datasets, and I want to reproduce the results reported at Table. 4. If I understand correctly, the evaluation is conducted with the VGG16 backbone and with a descriptor dimensions of 128. So I download your VGG16_128.pth, and run the eval.py by `python3 eval.py --dataset_folder ../SFXL --backbone vgg16 --fc_output_dim 128 --resume_model ../vgg16_128.pth`. It runs in 4hrs to finish evaluation, but I only got 

> < test - #q: 1000; #db: 2805815 >: R@1: 55.9, R@5: 67.2, R@10: 71.2, R@20: 75.4

It is different from the numbers in your paper. I wonder whether it is because of the ~10 files truncated, but I don't think it would cause such a big difference. 

I also want to get some clues to find out the root cause from my side. I would appreciate it if you can give me your evaluation results of VGG16_128.pth in the "small" version test dataset of SF-XL.

Can you help me with this issue? Thank you!

**Comment by gmberton** [comment]
Hello, the issue is due to the dimension of the descriptors.
In Table 4 the results are computed with descriptor dimension 512 (see the second column "Desc. dim."), so I think you should be able to reproduce the results by changing `--fc_output_dim 128 --resume_model ../vgg16_128.pth` to `--fc_output_dim 512 --resume_model ../vgg16_512.pth`.
By the way, why did you think that we used dimension 128 in Table 4? I can't find find any reference to that in the paper.
Let me know if it works :-)

**Comment by ShihaoShao-GH** [comment]
> Hello, the issue is due to the dimension of the descriptors. In Table 4 the results are computed with descriptor dimension 512 (see the second column "Desc. dim."), so I think you should be able to reproduce the results by changing `--fc_output_dim 128 --resume_model ../vgg16_128.pth` to `--fc_output_dim 512 --resume_model ../vgg16_512.pth`. By the way, why did you think that we used dimension 128 in Table 4? I can't find find any reference to that in the paper. Let me know if it works :-)

Sorry I read the paper from my phone last night and I am so tired. I skipped lines and see 512 from ResNet101. I am trying with 512 now. BTW, it seems that ResNet152-2048 gives me results of 0.0.

**Comment by ShihaoShao-GH** [comment]
> Hello, the issue is due to the dimension of the descriptors. In Table 4 the results are computed with descriptor dimension 512 (see the second column "Desc. dim."), so I think you should be able to reproduce the results by changing `--fc_output_dim 128 --resume_model ../vgg16_128.pth` to `--fc_output_dim 512 --resume_model ../vgg16_512.pth`. By the way, why did you think that we used dimension 128 in Table 4? I can't find find any reference to that in the paper. Let me know if it works :-)

UPDATE:
I can work with VGG16_512.pth with a even higher results in V1: `R@1: 66.1, R@5: 75.1, R@10: 77.6, R@20: 80.4`. Really appreciate it. But the 2048 issues remain.

**Comment by gmberton** [comment]
It's good to know that you solved your issue.
Regarding the ResNet152-2048, I have just tried it (downloading the weights from this repo) and it works fine, so I don't know what your issue could be. Let me know if I can help you somehow.

**Comment by ShihaoShao-GH** [comment]
> It's good to know that you solved your issue. Regarding the ResNet152-2048, I have just tried it (downloading the weights from this repo) and it works fine, so I don't know what your issue could be. Let me know if I can help you somehow.

I don't know why it still don't work for 2048. But I don't need to use that now. Maybe it is file broken issue or something. Thank you for your help anyway. Close this issue and I will re-open if I still need to fix it. (Or others can open a new one if they have the same issue)

**Comment by gmberton** [comment]
BTW, results on SF-XL test v1 with a ResNet-152-2048 are the following
`< test - #q: 1000; #db: 2805840 >: R@1: 83.6, R@5: 88.3, R@10: 90.0, R@20: 91.9`
