### ISSUE TITLE
Is the UTM coordinate of the picture in the SF-XL dataset the coordinate of the camera when taking the picture?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#17]
Is the orientation  the azimuth in coordinates?

**Comment by gmberton** [comment]
Yes, the UTM / GPS indicates the camera position. This is true for almost any visual geolocalization / place recognition dataset. And the orientation is the azimuth, ranging from 0° to 360° (0° means the camera points north, 180° the camera points south).

**Comment by wpumain** [comment]
Think you your reply
