### ISSUE TITLE
SF-XL

### ISSUE THREAD

**Issue by xuzhuang1996** [gmberton/CosPlace#2]
Hi, Thank you for your contribution.
I submitted the application for the SF-XL dataset, but many days passed without receiving any response from the task.
Do you know why? 
Thank you!

**Comment by gmberton** [comment]
Hi! We process all the requests within a few hours: if you sent a valid application you should have received an invitation days ago, make sure to check your Spam folder. A valid application should contain a real name (not name="aaa"), an institution, and an institutional email
