### ISSUE TITLE
Can you tell me how long it takes to train on about 900G raw data ?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#20]

**Comment by gmberton** [comment]
Have a look at [this issue](https://github.com/gmberton/CosPlace/issues/4)

**Comment by wpumain** [comment]
Is the time mentioned that all groups have participated in the calculation?

**Comment by wpumain** [comment]
Which of the trained models you provided has the largest amount of training data?

**Comment by gmberton** [comment]
That is the time that it takes to train the model to reproduce our results (trained on 8 groups).
All our models are trained on the same data. Probably the biggest models would benefit from training longer and on more groups

**Comment by wpumain** [comment]
N=5,L=2,N*N*L=5*5*2=50.All your  models are trained on the same data.So only 8 of the 50 groups participated in the training?Is the training data RAW or Processed?

**Comment by gmberton** [comment]
`So only 8 of the 50 groups participated in the training?` Yes.
To understand what the folders `raw` and `processed` are, read the README that you find in the dataset

**Comment by wpumain** [comment]
Think you for your help
