### ISSUE TITLE
Why only freeze  layers before conv_3 of ResNet？

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#21]
` backbone = get_pretrained_torchvision_model(backbone_name)
    if backbone_name.startswith("ResNet"):
        for name, child in backbone.named_children():
            if name == "layer3":  # Freeze layers before conv_3
                break
            for params in child.parameters():
                params.requires_grad = False
        logging.debug(f"Train only layer3 and layer4 of the {backbone_name}, freeze the previous ones")
        layers = list(backbone.children())[:-2]  # Remove avg pooling and FC layer`

Why only freeze  layers before conv_3 of ResNet？Train only layer3 and layer4 of the ResNet？If all layers participate in training, shouldn't the learning ability of this model be stronger?

**Comment by wpumain** [comment]
` backbone = get_pretrained_torchvision_model(backbone_name)
    if backbone_name.startswith("ResNet"):
        for name, child in backbone.named_children():
            if name == "layer3":  # Freeze layers before conv_3
                break
            for params in child.parameters():
                params.requires_grad = False
        logging.debug(f"Train only layer3 and layer4 of the {backbone_name}, freeze the previous ones")
        layers = list(backbone.children())[:-2]  # Remove avg pooling and FC layer`

**Comment by gmberton** [comment]
We freeze part of the model to speed up training and make it more lightweight. Note that this is common practice, and it is performed in basically any previous work (e.g. NetVLAD, SFRS).
I did not try to train the whole model, but I doubt that the results might improve significantly, because low-level features should be similar to the ones learned on ImageNet.

**Comment by wpumain** [comment]
Think you for you reply!
