### ISSUE TITLE
When the model makes predictions, what is the relationship between the number of images in the query dataset and the number of database images?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#22]
When the model makes predictions, what is the relationship between the number of images in the query dataset and the number of database images?For example, when I use this model to predict, there is only one image in the query dataset, so the image in the database dataset should be the image of the region where the query dataset image is located,to ensure the correctness, how many database images should be at least?

**Comment by gmberton** [comment]
You only need one database image near your query to find the query's position. If your first prediction is correct and the others are wrong, your recall is still 100%.
From the paper: `As a metric, we use the recall@N with a 25 meters threshold, i.e., the percentage of queries for which at least one of the first N predictions is within a 25 meters distance from the query, following standard procedure`

**Comment by wpumain** [comment]
Think you for your help
