### ISSUE TITLE
Where can I get Pitts250k data?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#25]
I didn't find a way to get the data from this article 【NetVLAD: CNN architecture for weakly supervised place recognition】。
Is this data obtained from here【https://github.com/Relja/netvlad/tree/master/datasets】?
But this URL does not introduce the structure of this data Pitts250k. 
Where is this data structure introduced?

**Comment by gmberton** [comment]
To download the datasets from the NetVLAD paper you should contact its authors, or open an issue on their repo, as we are not allowed to release it

**Comment by wpumain** [comment]
Think you for your help
