### ISSUE TITLE
How to add orientation to 360 degree panorama photo?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#26]
SF-XL dataset is segmented from 360 panoramas.In the process of segmentation, how to add the orientation?Also make sure that this orientation is the azimuth

**Comment by hello7623** [comment]
I think you can seperate the 360 degree image , the more images you sep, the better resulte may be.

**Comment by wpumain** [comment]
When dividing a 360-degree panoramic image, how to add azimuth data to the divided image? Because the CosPlace model training requires the azimuth data of the image.

**Comment by gmberton** [comment]
The heading of the panorama corresponds to the center of the image, so the center of a panorama with heading 180° points South. When you crop an image, the heading that you assign to each crop depends on how you crop it. If you use our script, the 12 crops are equally spaced (and partially overlapping) every 30°, going from 0° to 330°, and the correct heading is automatically assigned by the script.

**Comment by wpumain** [comment]
Thank you for your help. After listening to your explanation, I understand now. However, the heading of the cropped image and the heading of the full panorama image represent different meanings. The heading of the full panorama image represents the azimuth angle of the middle pixel of the image, while the heading of the cropped image represents the azimuth angle of the starting pixel, not the middle pixel of the image, right?

**Comment by gmberton** [comment]
Yes, your assumptions are correct :)

**Comment by wpumain** [comment]
Thank you very much for your help
