### ISSUE TITLE
Can you tell me what the name of the image file from the 【raw/train/panoramas】 data means?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#27]
For example, the file name of one of the image  from the 【raw/train/panoramas】 data  is:
@0545981.19@4184971.70@10@S@037.81098@-122.47762@rtCs5-P_9NGDzUbKyzStWA@@174@@@@201409@@.jpg
Are the numbers after the first @ symbol and the second @ symbol UTM coordinates?
That is, are 0545981.19 and 4184971.70 UTM coordinates?
Can you tell me what the numbers after the other @ symbols mean?

**Comment by wpumain** [comment]
Is the number 174 behind the 9th @ the azimuth of the panoramic photo? 
Since this photo is a 360 panoramic photo, how to understand the azimuth of this photo?

**Comment by gmberton** [comment]
Your assumptions are correct.
Each image is defined by its path, which contains all its metadata. The filename contains the metadata following the common format that we used in [our CVPR 2022 benchmark](https://github.com/gmberton/deep-visual-geo-localization-benchmark) (which is a separate paper than CosPlace) for multiple datasets:

@ UTM_easting @ UTM_northing @ UTM_zone_number @ UTM_zone_letter @ latitude @ longitude @ pano_id @ tile_num @ heading @ pitch @ roll @ height @ timestamp @ note @ extension

We used the @ as a separator because other characters might be contained in other fields (e.g. the "_" and "-" are contained in the pano_id. Note that for many images some of these values are empty.

**Comment by wpumain** [comment]
Thank you for your help. I have a question about the format of longitude and latitude. May I ask you?
      For latitude 037.81100, does it mean 37.81 1°?
      For longitude - 122.47763, it means - 122.47763 °?
      
________________________________
发件人: Gabriele Berton ***@***.***>
发送时间: 2023年2月27日 5:07
收件人: gmberton/CosPlace ***@***.***>
抄送: wpumain ***@***.***>; Author ***@***.***>
主题: Re: [gmberton/CosPlace] Can you tell me what the name of the image file from the 【raw/train/panoramas】 data means? (Issue #27)


Your assumptions are correct.
Each image is defined by its path, which contains all its metadata. The filename contains the metadata following the common format that we used in our CVPR 2022 benchmark<https://github.com/gmberton/deep-visual-geo-localization-benchmark> (which is a separate paper than CosPlace) for multiple datasets:

@ UTM_easting @ UTM_northing @ UTM_zone_number @ UTM_zone_letter @ latitude @ longitude @ pano_id @ tile_num @ heading @ pitch @ roll @ height @ timestamp @ note @ extension

We used the @ as a separator because other characters might be contained in other fields (e.g. the "_" and "-" are contained in the pano_id. Note that for many images some of these values are empty.

**Comment by gmberton** [comment]
The location of `37.811000, -122.477639` is equivalent to `37°48'39.6"N 122°28'39.5"W`.
We use the same format as in google maps, so if you paste on the google maps search bar `37.811000, -122.477639` it will point to the location of the image.

**Comment by wpumain** [comment]
Think you  for your help.
Best wishes for you.
________________________________
发件人: Gabriele Berton ***@***.***>
发送时间: 2023年2月27日 16:50
收件人: gmberton/CosPlace ***@***.***>
抄送: wpumain ***@***.***>; Author ***@***.***>
主题: Re: [gmberton/CosPlace] Can you tell me what the name of the image file from the 【raw/train/panoramas】 data means? (Issue #27)


The location of 37.811000, -122.477639 is equivalent to 37°48'39.6"N 122°28'39.5"W.
We use the same format as in google maps, so if you paste on the google maps search bar 37.811000, -122.477639 it will point to the location of the image.

―
