### ISSUE TITLE
How are these SF-XL   downloaded from Google Earth?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#28]
Can you share the method of downloading photos from Google Earth to make SF-XL dataset?

**Comment by gmberton** [comment]
We are not planning to release the code for downloading images from Google StreetView, although you can find some open-source repositories online that allow you to do that.

**Comment by wpumain** [comment]
Thank you for your help. May I ask you another question?
      When I get 360° panoramas from Google Earth, how can I get the metadata of these panoramas at the same time, such as azimuth, latitude and longitude values, etc.?
      Looking forward to your reply, thank you again.
