### ISSUE TITLE
Cannot open SF-XL datasat

### ISSUE THREAD

**Issue by seawavve** [gmberton/CosPlace#3]
I received the SF-XL dataset from e-mail but I cannot open the dataset.
there's the only text in below and any of download button or link.
So, How can I get the Dataset? Can you explain it?

'''
Hello,
--
thank you for your interest in our San Francisco eXtra Large dataset. If you like our work, don't forget to star our GitHub repository!
Check out what Berton Gabriele Moreno shared with you.
Open sf_xl
'''

**Comment by gmberton** [comment]
Hi, you just need to click on "Open sf_xl", it's a link to the dataset :)
Let me know if it works

**Comment by seawavve** [comment]
Omg Thank you ;) It works.
