### ISSUE TITLE
Why do I only perform Data Augmentation in CPU mode?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#31]
https://github.com/gmberton/CosPlace/blob/cea7de243abe1a59c69f1087b1b8001d01262c59/datasets/train_dataset.py#L62

```
if self.augmentation_device == "cpu":
            self.transform = T.Compose([
                    T.ColorJitter(brightness=args.brightness,
                                  contrast=args.contrast,
                                  saturation=args.saturation,
                                  hue=args.hue),
                    T.RandomResizedCrop([512, 512], scale=[1-args.random_resized_crop, 1]),
                    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
                ])
```
This means that there will be no Data Augmentation under the cuda model。
why?
Could we perform Data Augmentation in CPU mode and then transfer to GPU for deep neural network operations?

**Comment by gmberton** [comment]
Yes, using GPU is generally faster but it depends on the hardware.
You can pass `--augmentation_device cpu` and it will perform the augmentations on CPU and then pass the images to GPU, without affecting the results.

**Comment by wpumain** [comment]
Think you for your help!
