### ISSUE TITLE
Method for Downloading Historical Google Street View Images

### ISSUE THREAD

**Issue by AuderySun** [gmberton/CosPlace#34]
Hi@gmberton,
I've been closely following your work on visual geo-localization, and I am particularly intrigued by your methodology for acquiring historical Google Street View images.
Given that the Google Street View API doesn't offer a date option, I'd like to know how you downloaded these images.

Your insights would be greatly appreciated. Thank you very much!

**Comment by gmberton** [comment]
Hello @AuderySun, unfortunately we are not planning to release the code to download the data, this repo is only for CosPlace.
Sorry for the inconvenience.
