### ISSUE TITLE
License of trained weights?

### ISSUE THREAD

**Issue by Parskatt** [gmberton/CosPlace#35]
Hi! I can see that the code is licensed under the MIT license. 
Does this also apply to the weights of the trained model?

**Comment by gmberton** [comment]
Hi, thanks for asking. The model is trained on data from Google Street View, therefore the MIT license doesn't apply to the weights of the trained model

**Comment by Parskatt** [comment]
I think this is worth mentioning in the LICENSE. For example it would mean that anyone using your model for e.g. the image matching challenge would be automatically disqualified.

I'm also wondering about the data from google street view, from my recollection they do not allow creating datasets:

<img width="724" alt="image" src="https://github.com/gmberton/CosPlace/assets/22053118/acbe2979-c379-47b8-9992-455e3227e71b">

Source: https://www.google.com/intl/en-GB_ALL/permissions/geoguidelines/

Am I misinterpreting what google is saying in these guidelines?

**Comment by gmberton** [comment]
Hi @Parskatt somehow I came across this issue again and realized I never replied.
I honestly don't know if training a model on Google data would make the weights non-MIT licensed. Do you have any experience with that?
My only take is that IF training on non-MIT data makes a model non-MIT, then every VPR model's weights are non-MIT, as they all train on Google Street View data, including NetVLAD, CosPlace, MixVPR, EigenPlaces, AnyLoc, Conv-AP, SALAD, CliqueMining, and pretty much any VPR model that I can think of.

**Comment by gmberton** [comment]
Ok I've read about this a bit and it seems to be mostly fine, at least in the US (I couldn't find information about other countries). [Here is a link](https://medium.com/towards-data-science/the-most-important-supreme-court-decision-for-data-science-and-machine-learning-44cfc1c1bcaf) to a case where Google used copyrighted data to train a model to use for commercial use, and the Supreme Court said it's fine.
So I'd say you can use any NetVLAD or CosPlace for your IMC 2025 submission :)

**Comment by Parskatt** [comment]
Hi!

I think the precedent is not yet set.

Regarding IMC it is a bit funny since Google has been a sponsor of the competition. Perhaps in some ways it works out for them, since they would always be able to use their own stuff :)

In general I would probably leave a disclaimer around the datasets model was trained on and make clear that its up to the user to make sure that their usage of the weights is permissable.
