### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by Orbis36** [gmberton/CosPlace#4]
Hello, 

Thanks for your work.
Since it's a really big dataset, Could you please tell us your training time on what kind of GPU?

Thanks

**Comment by gmberton** [comment]
Hello,

note that although the dataset is very big, most of the images are not used at training time, which allows to train the model fast.
Training a ResNet-18 on a 3090 takes 20 hours on one RTX 3090, while a ResNet-101 on the same architecture takes around 75 hours.
Training a ResNet-18 on an old machine (one GTX 1080 and 3 CPU cores) takes around 55 hours.

I hope this helps

**Comment by huachaoguang** [comment]
That's surprised, it's so quickly!
