### ISSUE TITLE
Question about the 'groups_num' for training.

### ISSUE THREAD

**Issue by Devoe-97** [gmberton/CosPlace#40]
Hello, thanks for sharing the dataset. 
I read in the paper that ablation experiments showed the best results were achieved using 8 groups. 
I'm confused as to why just the first 8 groups are used instead of using some of the most training-friendly groups out of the 50.

**Comment by gmberton** [comment]
That's a good question. I actually tried selecting 8 random groups or 8 "uniformly spaced" groups (e.g. the 0th, 6th, 12th...) but it did not improve the results much, if at all. My guess is that the information contained in a group is not too different from information contained in any other group, which would explain why results with 1 group are already almost as good as using 8 groups.
The difference between group 0 and group 2 is just a shift of 20 meters, but the areas (in terms of domains/architectures) of the city that are contained in group 0 and 2 are pretty much the same.
I hope this answers your question, but feel free to play with the chosen groups and you might get better results!

**Comment by Devoe-97** [comment]
Thanks for your quick reply. It answered my question.
