### ISSUE TITLE
Can't download small version of dataset...

### ISSUE THREAD

**Issue by rocker12121** [gmberton/CosPlace#44]
Hello. Thanks for your work. I have applied for the dataset through online form and got a readme file to download the dataset. But i can't figure out how to download the small version (5gb) of the dataset. 

Looking forward for the response. Thank you!

**Comment by gmberton** [comment]
Hi, you can simply run this command to download the small version, as written in the README.
```
rsync -rhz --info=progress2 --ignore-existing rsync://vandaldata.polito.it/sf_xl/small .
```

**Comment by rocker12121** [comment]
Thanks for your help. I am successfully done with the training by changing some parameters as per my requirement. But my final goal in a little bit different.

I am mainly working with the 3D lidar. I convert the lidar point cloud to lidar intensity image or lidar range image (one of these), which is a panoramic image. So my questions is: can i modify and train this network model for lidar images?

Here is an example of how my lidar image looks like:
![2](https://github.com/gmberton/CosPlace/assets/17266476/d7a375bf-4805-4ba8-9b43-6aaed3357bbd)

**Comment by gmberton** [comment]
Hi, you can simply use convert those images to RGB and the code will work, as long as the images/crops have the required metadata in the filename (check [this issue](https://github.com/gmberton/CosPlace/issues/43)).
I'm not sure if that will achieve good results though
