### ISSUE TITLE
do image retrieval on my own dataset

### ISSUE THREAD

**Issue by xuxumiao777** [gmberton/CosPlace#45]
Can I just use pretrained model to do image_retrieval on my dataset.
For example, I have a image folder A containing about 500 images. and now given a list of query images, I want to find k-nearest images in A for a query image. How can I do that without retraining the model?

Thank you in advance!

**Comment by gmberton** [comment]
There is no way to do it on the CosPlace repo but you do it on this other repo 
https://github.com/gmberton/VPR-methods-evaluation

**Comment by xuxumiao777** [comment]
> There is no way to do it on the CosPlace repo but you do it on this other repo

Thanks，that is exactly what i need.
