### ISSUE TITLE
Issues about dataset download speed

### ISSUE THREAD

**Issue by dl857** [gmberton/CosPlace#47]
Hi, thank you for creating such a great dataset!
I ran into an issue while following your method to download the dataset. The download speed is too slow, only tens of kB/s, which takes hundreds or thousands of hours to complete. I have confirmed that there is no problem with my network, I would like to know if this is normal? Is there any way to speed up my download?
Thank you in advance.

**Comment by gmberton** [comment]
Sometimes the server hosting the data is used for other I/O heavy processes, resulting in slow download speed for other users. Usually these issues end within hours to days (rarely). Let me know if the issue persists, although I think it should be resolved by now

**Comment by dl857** [comment]
您发给我的信件已收到。

**Comment by shuimushan** [comment]
> 您发给我的信件已收到。

请问你有没有成功下载呀？我也是网速很慢而且不稳定，总是几十kB/s到几百kB/s

**Comment by dl857** [comment]
您发给我的信件已收到。

**Comment by naoki-17** [comment]
Hi Berton, thanks for your dataset.
The issue persists for latest days for me. It will cost many days to download all datasets, so I'm sorry to ask if there any way to speed up? Thanks very much if you have any idea for help.

**Comment by dl857** [comment]
您发给我的信件已收到。

**Comment by gmberton** [comment]
Hi, some days the download speed is very slow due to the server being used internally, but most of the time the speed should be sufficient to download in 1-2 days
