### ISSUE TITLE
Question about the number of 'group'

### ISSUE THREAD

**Issue by hmf21** [gmberton/CosPlace#5]
Hi @gmberton :
Thanks for your impressive work and sharing code. I am wondering what is the meaning of hyperparameter 'groups'. Can I set the value of 'group' to 1 for the SF-XL dataset? What is the difference between one group and eight groups for training?
Hope for your reply!

**Comment by gmberton** [comment]
Hi, thanks for your interest!
Yes, the value of groups can be set to 1. On [the paper](https://arxiv.org/pdf/2204.02287.pdf) you can find an ablation over the number of groups at Figure 10: the rightmost plot shows that when using 1 group instead of 8 the results are about 1% lower.
