### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by spirit71** [gmberton/CosPlace#50]
Hello, I want to use the dataset in the code base for research, but there is a problem that the server is not opened during the access process. Can you please open the server of the dataset code?

**Comment by spirit71** [comment]
Hi, Thank you for your contribution.
I submitted the application for the SF-XL dataset, but many days passed without receiving any response from the task.
Do you know why?
Thank you!

**Comment by gmberton** [comment]
Hi, the server was offline for a few hours during the night, it's online now. There you will find all the information needed to download the dataset
