### ISSUE TITLE
Question about testing image size.

### ISSUE THREAD

**Issue by hao-qiang** [gmberton/CosPlace#6]
Great job! Should I resize image to 256x256 when testing.

**Comment by gmberton** [comment]
Thank you!
Training images have resolution 512x512, so it is probably better that test images have a similar resolution to training images (e.g. 512x512 or 480x640). For our experiments at test time we used the standard resolution used for each datasets (e.g. for Pitts30k 480x640). You can try 256x256 but it would probably perform worse than with higher resolutions
