### ISSUE TITLE
using in remote sensing visual place recognition

### ISSUE THREAD

**Issue by rafal7466** [gmberton/CosPlace#9]
Hi
Can we use CosPlace for remote sensing VPR? image is taken from down facing camera mounted in an airplane.

**Comment by gmberton** [comment]
Hi,
I think the training procedure should be modified, CosPlace is unlikely to work out of the box on aerial images. Also, just using the model trained on San Francisco eXtra Large does not give good results.
You can have a look at [this other issue](https://github.com/gmberton/CosPlace/issues/8) for more info and results.
